### ISSUE TITLE
alternative to scanning packages folder?

### ISSUE THREAD

**Issue by sethladd** [MikeMitterer/dart-stagedive#1]
The README wasn't very clear, but there might be a long-term issue with scanning the packages folder.

Soon, because we're adding a .packages file (see https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md), there won't be a `packages/` directory in the root of your project.

An alternative is to scan through the installed packages in the pub-cache. Luckily, there's a package for that: https://github.com/dart-lang/pub_cache

Maybe dart-stagedive should scan through all installed packages in pub-cache?

**Comment by MikeMitterer** [comment]
Thanks - is already solve.
